import type { Section } from './types';

export const defaultSections: Section[] = [
  { id: 's0', name: '"Что выведет"', topics: [
    { id: 't0_0', n: 'Hoisting (var/let/функции)', p: 'high' },
    { id: 't0_1', n: 'Замыкания в циклах (var vs let)', p: 'high' },
    { id: 't0_2', n: 'this в разных контекстах', p: 'high' },
    { id: 't0_3', n: 'Порядок async (микро/макротаски)', p: 'high' },
    { id: 't0_4', n: 'Приведение типов (== ловушки)', p: 'high' },
    { id: 't0_5', n: 'Мутации vs ссылки', p: 'med' },
    { id: 't0_6', n: 'Прототипы (что найдётся)', p: 'med' },
    { id: 't0_7', n: 'Числа: 0.1+0.2, NaN, Infinity', p: 'med' },
    { id: 't0_8', n: 'Деструктуризация edge cases' },
  ]},
  { id: 's1', name: 'CSS / Верстка', topics: [
    { id: 't1_0', n: 'Box model, специфичность, каскад' },
    { id: 't1_1', n: 'Flexbox' },
    { id: 't1_2', n: 'CSS Grid' },
    { id: 't1_3', n: 'Позиционирование, stacking context, z-index' },
    { id: 't1_4', n: 'Адаптивность (media queries, mobile-first)' },
    { id: 't1_5', n: 'Центрирование (все способы)' },
    { id: 't1_6', n: 'CSS переменные' },
    { id: 't1_7', n: 'Псевдоклассы / псевдоэлементы' },
    { id: 't1_8', n: 'Единицы: rem/em/vh/vw/clamp' },
    { id: 't1_9', n: 'Repaint vs Reflow' },
    { id: 't1_10', n: 'Container queries, modern CSS' },
  ]},
  { id: 's2', name: 'Анимации', topics: [
    { id: 't2_0', n: 'CSS transitions / animations' },
    { id: 't2_1', n: 'transform, will-change' },
    { id: 't2_2', n: 'requestAnimationFrame' },
    { id: 't2_3', n: 'Framer Motion' },
    { id: 't2_4', n: 'Анимация transform/opacity (GPU)' },
  ]},
  { id: 's3', name: 'SCSS / Методологии', topics: [
    { id: 't3_0', n: 'SCSS: переменные, вложенность, миксины' },
    { id: 't3_1', n: 'BEM' },
    { id: 't3_2', n: 'CSS Modules' },
    { id: 't3_3', n: 'Tailwind' },
    { id: 't3_4', n: 'CSS-in-JS (styled-components, emotion)' },
    { id: 't3_5', n: 'Сравнение подходов, trade-offs' },
  ]},
  { id: 's4', name: 'Сборщики / Тулинг', topics: [
    { id: 't4_0', n: 'Webpack (loaders, plugins)' },
    { id: 't4_1', n: 'Vite (esbuild + rollup)' },
    { id: 't4_2', n: 'Module systems (ESM, CommonJS)' },
    { id: 't4_3', n: 'Babel, транспиляция' },
    { id: 't4_4', n: 'esbuild / SWC / Turbopack' },
    { id: 't4_5', n: 'Source maps' },
    { id: 't4_6', n: 'PostCSS, autoprefixer' },
  ]},
  { id: 's5', name: 'Git', topics: [
    { id: 't5_0', n: 'merge vs rebase' },
    { id: 't5_1', n: 'Разрешение конфликтов' },
    { id: 't5_2', n: 'reset / revert / cherry-pick' },
    { id: 't5_3', n: 'Git flow, ветвление' },
    { id: 't5_4', n: 'interactive rebase, squash' },
  ]},
  { id: 's6', name: 'JavaScript', topics: [
    { id: 't6_0', n: 'Event Loop, microtask/macrotask' },
    { id: 't6_1', n: 'Promise + реализации' },
    { id: 't6_2', n: 'async/await + генераторы' },
    { id: 't6_3', n: 'Closures, scope, hoisting, TDZ' },
    { id: 't6_4', n: 'this, bind/call/apply' },
    { id: 't6_5', n: 'Прототипы, наследование, new' },
    { id: 't6_6', n: 'debounce/throttle' },
    { id: 't6_7', n: 'WeakMap / WeakRef' },
    { id: 't6_8', n: 'Symbol, итераторы' },
    { id: 't6_9', n: 'Proxy / Reflect' },
    { id: 't6_10', n: 'Immutability' },
  ]},
  { id: 's7', name: 'React', topics: [
    { id: 't7_0', n: 'Reconciliation, Fiber' },
    { id: 't7_1', n: 'useEffect (race condition, cleanup)' },
    { id: 't7_2', n: 'useMemo / useCallback' },
    { id: 't7_3', n: 'Context (перформанс)' },
    { id: 't7_4', n: 'Compound / HOC / Render Props' },
    { id: 't7_5', n: 'useTransition / useDeferredValue' },
    { id: 't7_6', n: 'Error Boundaries' },
    { id: 't7_7', n: 'forwardRef / useImperativeHandle' },
    { id: 't7_8', n: 'useReducer', p: 'med' },
    { id: 't7_9', n: 'Portals, Strict Mode' },
  ]},
  { id: 's8', name: 'Next.js', topics: [
    { id: 't8_0', n: 'Server vs Client Components' },
    { id: 't8_1', n: 'SSR/SSG/ISR/CSR' },
    { id: 't8_2', n: 'Streaming + Suspense' },
    { id: 't8_3', n: 'Server Actions' },
    { id: 't8_4', n: 'Middleware, Auth' },
    { id: 't8_5', n: 'prefetch + HydrationBoundary' },
    { id: 't8_6', n: 'revalidate, 4 уровня кеша' },
    { id: 't8_7', n: 'Edge vs Node Runtime', p: 'med' },
    { id: 't8_8', n: 'Parallel / Intercepting Routes', p: 'med' },
    { id: 't8_9', n: 'next/image' },
  ]},
  { id: 's9', name: 'TypeScript', topics: [
    { id: 't9_0', n: 'interface vs type, Generics' },
    { id: 't9_1', n: 'Utility Types' },
    { id: 't9_2', n: 'Type Guards, predicates' },
    { id: 't9_3', n: 'Discriminated Union' },
    { id: 't9_4', n: 'keyof, typeof, infer' },
    { id: 't9_5', n: 'Conditional + Mapped Types' },
    { id: 't9_6', n: 'unknown / any / never' },
    { id: 't9_7', n: 'Template Literal Types' },
    { id: 't9_8', n: 'satisfies, declaration merging' },
  ]},
  { id: 's10', name: 'State / Формы', topics: [
    { id: 't10_0', n: 'Zustand, Redux Toolkit' },
    { id: 't10_1', n: 'React Query / SWR' },
    { id: 't10_2', n: 'Optimistic updates' },
    { id: 't10_3', n: 'Типы стейта, флоу данных' },
    { id: 't10_4', n: 'React Hook Form + Zod' },
    { id: 't10_5', n: 'Async валидация форм', p: 'med' },
    { id: 't10_6', n: 'XState, Jotai' },
  ]},
  { id: 's11', name: 'Тестирование', topics: [
    { id: 't11_0', n: 'Jest / Vitest (unit)', p: 'high' },
    { id: 't11_1', n: 'React Testing Library', p: 'high' },
    { id: 't11_2', n: 'MSW', p: 'high' },
    { id: 't11_3', n: 'Playwright / Cypress', p: 'med' },
    { id: 't11_4', n: 'Storybook' },
  ]},
  { id: 's12', name: 'Сети', topics: [
    { id: 't12_0', n: 'HTTP/1.1 vs 2 vs 3' },
    { id: 't12_1', n: 'CORS, preflight' },
    { id: 't12_2', n: 'XSS, CSRF, CSP' },
    { id: 't12_3', n: 'WebSocket / SSE / Polling' },
    { id: 't12_4', n: 'HTTP кэширование' },
    { id: 't12_5', n: 'REST vs GraphQL vs tRPC', p: 'high' },
    { id: 't12_6', n: 'OAuth flow детально', p: 'med' },
    { id: 't12_7', n: 'CI/CD, Docker', p: 'med' },
  ]},
  { id: 's13', name: 'Browser / Web APIs', topics: [
    { id: 't13_0', n: 'Web Workers / Service Workers', p: 'high' },
    { id: 't13_1', n: 'Хранилище (localStorage/IndexedDB)', p: 'high' },
    { id: 't13_2', n: 'Intersection / Resize Observer', p: 'med' },
    { id: 't13_3', n: 'Critical Rendering Path', p: 'med' },
    { id: 't13_4', n: 'Resource hints (preload/prefetch)', p: 'med' },
    { id: 't13_5', n: 'Performance API' },
  ]},
  { id: 's14', name: 'Архитектура', topics: [
    { id: 't14_0', n: 'Feature Sliced Design' },
    { id: 't14_1', n: 'Atomic Design' },
    { id: 't14_2', n: 'Module Federation / Microfrontends' },
    { id: 't14_3', n: 'Monorepo (Nx, Turborepo)', p: 'med' },
    { id: 't14_4', n: 'Design Tokens' },
  ]},
  { id: 's15', name: 'Производительность', topics: [
    { id: 't15_0', n: 'Core Web Vitals' },
    { id: 't15_1', n: 'Code splitting, tree shaking' },
    { id: 't15_2', n: 'Виртуализация, lazy loading' },
    { id: 't15_3', n: 'React Profiler + DevTools', p: 'med' },
    { id: 't15_4', n: 'Font loading, critical CSS' },
  ]},
  { id: 's16', name: 'Дизайн-паттерны', topics: [
    { id: 't16_0', n: 'Observer / Pub-Sub', p: 'med' },
    { id: 't16_1', n: 'Singleton', p: 'med' },
    { id: 't16_2', n: 'Factory' },
    { id: 't16_3', n: 'Strategy' },
    { id: 't16_4', n: 'Module pattern' },
    { id: 't16_5', n: 'Decorator' },
  ]},
  { id: 's17', name: 'Accessibility (a11y)', topics: [
    { id: 't17_0', n: 'Семантический HTML', p: 'med' },
    { id: 't17_1', n: 'ARIA атрибуты', p: 'med' },
    { id: 't17_2', n: 'Keyboard navigation', p: 'med' },
    { id: 't17_3', n: 'Focus management', p: 'med' },
    { id: 't17_4', n: 'Screen readers' },
  ]},
  { id: 's18', name: 'SEO', topics: [
    { id: 't18_0', n: 'Meta tags, Open Graph', p: 'med' },
    { id: 't18_1', n: 'SSR/SSG для SEO', p: 'med' },
    { id: 't18_2', n: 'Next.js metadata API', p: 'med' },
    { id: 't18_3', n: 'Structured data' },
    { id: 't18_4', n: 'sitemap, robots.txt' },
  ]},
  { id: 's19', name: 'Утилитарные знания', topics: [
    { id: 't19_0', n: 'Регулярные выражения', p: 'med' },
    { id: 't19_1', n: 'Работа с датами (date-fns)', p: 'med' },
    { id: 't19_2', n: 'Числа и точность (float, BigInt)', p: 'med' },
    { id: 't19_3', n: 'i18n / Intl API', p: 'med' },
    { id: 't19_4', n: 'Функциональное программирование' },
  ]},
  { id: 's20', name: 'Мониторинг', topics: [
    { id: 't20_0', n: 'Sentry (error tracking)', p: 'med' },
    { id: 't20_1', n: 'Web Vitals в проде', p: 'med' },
    { id: 't20_2', n: 'npm audit, dependency security' },
  ]},
  { id: 's21', name: 'Алгоритмы', topics: [
    { id: 't21_0', n: 'Хеш-таблицы, Two Sum' },
    { id: 't21_1', n: 'Sliding Window, Two Pointers' },
    { id: 't21_2', n: 'Stack, Big O' },
    { id: 't21_3', n: 'BFS / DFS (деревья, графы)', p: 'high' },
    { id: 't21_4', n: 'Binary Search', p: 'high' },
    { id: 't21_5', n: 'Dynamic Programming', p: 'med' },
    { id: 't21_6', n: 'Структуры данных (LRU, Trie, Heap)', p: 'med' },
  ]},
];

// Topics marked done in the original progress file
export const defaultDoneIds: string[] = [
  't1_0','t1_1','t1_2','t1_3','t1_4','t1_5','t1_6','t1_7','t1_8','t1_9','t1_10',
  't2_0','t2_1','t2_2','t2_3','t2_4',
  't3_0','t3_1','t3_2','t3_3','t3_4','t3_5',
  't4_0','t4_1','t4_2','t4_3','t4_4','t4_5','t4_6',
  't5_0','t5_1','t5_2','t5_3','t5_4',
  't6_0','t6_1','t6_2','t6_3','t6_4','t6_5','t6_6','t6_7','t6_8','t6_9','t6_10',
  't7_0','t7_1','t7_2','t7_3','t7_4','t7_5','t7_6','t7_7',
  't8_0','t8_1','t8_2','t8_3','t8_4','t8_5','t8_6',
  't9_0','t9_1','t9_2','t9_3','t9_4','t9_5','t9_6','t9_7',
  't10_0','t10_1','t10_2','t10_3','t10_4',
  't12_0','t12_1','t12_2','t12_3','t12_4',
  't14_0','t14_1','t14_2',
  't15_0','t15_1','t15_2',
  't21_0','t21_1','t21_2',
];
